name: flutter_note
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  
  # Database Lokal
  sqflite: ^2.4.2
  sqflite_common_ffi: ^2.3.6
  sqflite_common_ffi_web: ^1.0.1+2
  
  # Firebase & Google Login (INI YANG TADI HILANG)
  firebase_core: ^3.0.0
  cloud_firestore: ^5.0.0
  firebase_auth: ^5.0.0
  google_sign_in: ^7.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true